### ISSUE TITLE
Question: Selective non-sync of certain groups and channels

### ISSUE THREAD

**Issue by BrandonKMLee** [knadh/tg-archive#10]
For privacy, some items should not pass through the bot. Having the right to choose is useful.

**Comment by knadh** [comment]
The simplest way to do this is to open the `.sqlite` DB and delete or blank out the messages in it. This can be scripted or can be done manually with a tool like https://sqlitebrowser.org

**Comment by BrandonKMLee** [comment]
@knadh perhaps a few pieces of helper code in python? Would that work?

**Comment by knadh** [comment]
The table structures are described here: https://github.com/knadh/tg-archive/blob/e97016f9a0fc21eaf6b0ca2d22a85a308c12d671/tgarchive/db.py#L10

With the `sqlite3` CLI, you can do:

```
> sqlite3 data.sqlite
> DELETE FROM messages WHERE id IN (1,2,3 ...);

# Exit with Ctrl+D
```
Python script, you can can refer to `db.py` or myriads of Python+SQLite tutorials out there. You just have to open the file and execute the DELETE statement with ids of messages you want to remove.

**Comment by BrandonKMLee** [comment]
Will write some code and then PR that to you guys, because this is kind of a make-or-breaker.
