### ISSUE TITLE
admin / channel messages in supergroup

### ISSUE THREAD

**Issue by mouflon72** [knadh/tg-archive#102]
hi,
thank you for this great tool!
i am trying to archive a supergroup, but the messages posted in the name of the group don't show up in the archive.
as supergroup is technically a channel, that would be messages posted by the channel probably.
the messages are also not present in the database.
any chance to get this fixed?
best regards

**Comment by knadh** [comment]
Thank you. I'm unsure if the `telethon` lib supports this. Don't have time to explore this, unfortunately.
