### ISSUE TITLE
Question: Windows installation vs Chocolatey package

### ISSUE THREAD

**Issue by BrandonKMLee** [knadh/tg-archive#11]
Is there a better way to set this up to other than directly tampering config files?
Chocolatey is gear more towards easy-builds.

**Comment by knadh** [comment]
`pip install tg-archive` is the easiest way to install, provided you have Python and pip setup on windows. There is no config file involved in the installation.

I'm not familiar with Chocolatey. If there's a way to package tg-archive in that for Windows, please feel free to send a PR!

**Comment by BrandonKMLee** [comment]
Does step 2 in https://github.com/knadh/tg-archive#usage requires that the phone is present for text messages?

**Comment by knadh** [comment]
Yes. Telegram seems to require the phone number to send the auth code for the first connection.
