### ISSUE TITLE
template.html showing variables

### ISSUE THREAD

**Issue by scarlion1** [knadh/tg-archive#111]
If I follow your Usage instructions to build "mysite" what's the proper way to publish it?  I copied `config.yaml`, `rss_template.html`, `site/`, `static/`, and `template.html` to Web Root but `/template.html` renders as shown below.  Also tried putting the whole `mysite` dir in the Web Root but `/mysite/template.html` still looks the same.  What I mess up?  Thx

![Screenshot from 2023-09-10 22-20-36](https://github.com/knadh/tg-archive/assets/2446600/81c3aeb4-83be-411a-9733-eb2a6d5658f7)

**Comment by knadh** [comment]
That's the raw template that's showing. After you generate `mysite` directory:
- Edit config.yaml to add your settings
- Run `tgarchive --sync` in the directory to sync data from Telegram to your local system.
- Run `tgarchive --build` to generate the site. A new directory `site` is created with the HTML files that you can publish.

**Comment by scarlion1** [comment]
Awesome!  Everything is rendering now except for the name of the group.  In my config, `group` is set to the group ID, so `-100...` and that's what shows underneath the icon on the published site, instead of the name of the group:
```
@-100... / 
Public archive of 
Telegram messages. 
```
How to get that to show the name of the group?

**Comment by scarlion1** [comment]
Awesome!  Everything is rendering now except for the name of the group.  In my config, `group` is set to the group ID, so `-100...` and that's what shows underneath the icon on the published site, instead of the name of the group:
```
@-100... / 
Public archive of 
Telegram messages. 
```
@knadh  How to get that to show the name of the group?

**Comment by scarlion1** [comment]
I guess I was mistaken in remembering the https://tg.fossunited.org/ example and it's more readable & memorable when group has an `@name`.

In this case, I guess have to add to `config.yaml` some new variables, e.g. `group_name` and `group_link` and go from there...
