### ISSUE TITLE
Config.yaml not allowing multiple groups?

### ISSUE THREAD

**Issue by BrandonKMLee** [knadh/tg-archive#13]
When loading the app, `group: "your_group_name"` is the default, it seems that that the software did not make a note on archiving multiple groups or channels.

**Comment by knadh** [comment]
If you have multiple groups, you should create multiple config's for each group. eg: `mygroup.yaml`, `mygroup2.yaml`.

Don't forget to use different directories for storing media for different groups (`media_dir`) across these config files, and also use a different data file for each group when calling tg-archive `--data`.

**Comment by BrandonKMLee** [comment]
@knadh it might sound weird to be asking for a generator that can spawn these en masse.

**Comment by knadh** [comment]
This can be done easily with some external scripting. Doesn't make sense to add config template generation to the core.
