### ISSUE TITLE
Overlapping Divs, Extra white space on left making the page scroll horizontally

### ISSUE THREAD

**Issue by srikanthlogic** [knadh/tg-archive#2]
Posting some screenshots. The page looks fine when on 67% font size, but breaks like below when viewed on 100%. There appears to be too much of whitespace on the left though while the page has a horizontal scroll bar.

My current resolution : 
```bash
$ xdpyinfo | awk '/dimensions/ {print $2}'
1920x1080

```

![image](https://user-images.githubusercontent.com/126862/111893005-da8c8f80-8a25-11eb-9a11-c297bd0adc85.png)
![image](https://user-images.githubusercontent.com/126862/111893057-19bae080-8a26-11eb-8516-27b7be72061a.png)
![image](https://user-images.githubusercontent.com/126862/111893034-f4c66d80-8a25-11eb-8fc2-9775803258f1.png)
![image](https://user-images.githubusercontent.com/126862/111893157-a9608f00-8a26-11eb-844c-099d6a090f45.png)

**Comment by knadh** [comment]
There’s a min-width on body, so it shouldn’t wrap like this ideally. What browser is this?

**Comment by srikanthlogic** [comment]
I was using Brave. When tried on Firefox the horizontal scroll doesn't come up, but there is lot more room on the left and there is overlap of the group name div.
![image](https://user-images.githubusercontent.com/126862/111893996-06f7da00-8a2d-11eb-8c12-64056f593eb9.png)
