### ISSUE TITLE
Support for polls

### ISSUE THREAD

**Issue by srikanthlogic** [knadh/tg-archive#3]
Polls aren't currently supported and appear as blank messages.

![image](https://user-images.githubusercontent.com/126862/111893274-a023f200-8a27-11eb-809b-cdd5d00dbdb6.png)

**Comment by knadh** [comment]
Will explore this 👍🏽

**Comment by knadh** [comment]
https://github.com/knadh/tg-archive/commit/1f84fef6ec4c8b5bddf42772a3627f2c8c8172f6 adds poll support. There's also a new `--sync=ID` flag that can be used to re-sync a message in case it has to be refreshed, like a long standing poll.

![image](https://user-images.githubusercontent.com/547147/112006038-592e1d80-8b49-11eb-9621-38f3f5a20560.png)
