### ISSUE TITLE
Incorrect sort order for years in sidebar

### ISSUE THREAD

**Issue by joschi** [knadh/tg-archive#34]
I'm using tg-archive 0.3.9 with a Telegram group which existed for a few years already.

When creating the static website with `tg-archive --build`, the generated sidebar is sorting the years in the sidebar incorrectly (see screenshot).

<img width="60" alt="Sort order in sidebar" src="https://user-images.githubusercontent.com/43951/139667274-73e3d1e3-968b-4e8c-a084-73b76af79930.png">

**Comment by knadh** [comment]
Whew, that's curious.

1) Have you made any changes to the template?
2) Is it a public group whose data can  be shared? If yes, could upload the `data.sqlite` file here? I can try and reproduce and debug the issue.

**Comment by joschi** [comment]
> Have you made any changes to the template?

No, I haven't changed the template.

> Is it a public group whose data can be shared? If yes, could upload the data.sqlite file here? I can try and reproduce and debug the issue.

The group is https://t.me/clickhouse_en and I think sharing the data is fine.
🔗 [`data.sqlite.gz`](https://github.com/knadh/tg-archive/files/7453172/data.sqlite.gz)

**Comment by knadh** [comment]
Found the issue. Please upgrade to `v3.1.0`

**Comment by joschi** [comment]
@knadh Thanks for the quick fix!

I can confirm that tg-archive 0.3.10 is indeed fixing the sorting issue:
https://tg-clickhouse-archive.netlify.app/clickhouse_en/
