### ISSUE TITLE
New Function

### ISSUE THREAD

**Issue by KenKout** [knadh/tg-archive#36]
Hi owner, could you please add export date like telegram ? As I know, telegram has given owner of the groups to disable/enable function export data on official app. So I came to this tool and it works very well. But it exports all message, so it runs very slow and I dont really need the previous message too much.
So coud you please add it ? Thank you very much and sorry if I disturbing you.
![image](https://user-images.githubusercontent.com/54569460/144442393-2ac9f7cd-2848-4e75-88e7-5663977354f6.png)

**Comment by knadh** [comment]
[Added](https://github.com/knadh/tg-archive/commit/6edeaf701cc994a724eb28600385a13dd8c0a5af) a new `--from-id` flag. Please pip upgrade tg-archive to `v0.5.0`

1. Open your group in the browser on https://web.telegram.org
2. Right click on a message from the date where you want to start importing and click on "Copy message link".
   ![image](https://user-images.githubusercontent.com/547147/144452610-f180af38-ecd1-470f-830a-5e0db3006e77.png)
3. From the copied message link, get the numeric ID of the message. eg: `https://t.me/yourgroup/17227` (17727 is the ID)
4. When running tg-archive, pass this ID. `--tg-archive --sync --from-id=17727`. Only messages from this point will be fetched.

Thanks.
