### ISSUE TITLE
Configurable Privacy Options

### ISSUE THREAD

**Issue by srikanthlogic** [knadh/tg-archive#4]
While discussing this project + chat privacy in general, we (at [CashlessConsumer](https://t.me/CashlessConsumer)) had a small discussion around chat privacy and it will be useful for this project to have configurable privacy options so that this can serve varied groups which have different privacy needs.

![image](https://user-images.githubusercontent.com/126862/111893839-94d2c580-8a2b-11eb-95c6-b988687467ed.png)

Posting some initial thoughts on this 
1. Option to show / hide timestamp - the template can show / hide timestamp based on this.
2. Link Mode :- Option to pick only links / media and scrub off any comments. This lets the group archive only resources while skipping the chatter. This lets community have freedom to chat, prevents chatty noise on archives, while preserving value. This can be True / False
3. Include / Exclude from archives based on select hashtags - If LinkMode is True, a set of hashtags can be added as 'Include' hashtags so those important messages get archived, wihle leaving out remaining chats. If LinkMode is False, a set of hashtags can be added to 'Exclude' hashtag (like #DontArchive #KeepThisPrivate), so that the group can still have private non-archiving conversations even while on Full Archive mode.

Thoughts?

**Comment by mr-karan** [comment]
> "This is a privacy risk, lets stay as is"

Just setting some context, this was [discussed](https://tg.fossunited.org/2021-03_5.html#6674) in Foss United as well before publishing the archive. Like @knadh mentioned, for an already public Telegram group, the chats are available publicly anyway.

**Comment by knadh** [comment]
About privacy, like @mr-karan pointed out, by definition, there is no privacy in a public Telegram group. Anyone can join and read/export/copy/re-publish messages at any point.

> Option to pick only links / media and scrub off any comments

This is too niche an option to include in the global config, but can be easily achieved externally by doing a `DELETE from messages WHERE media_id is NULL` on the .sqlite file.

> Include / Exclude from archives based on select hashtags

Again, too specific to include in the config but can be easily achieved by querying the .sqlite file.

These can be done with the [SQLite CLI](https://sqlite.org/cli.html).
