### ISSUE TITLE
Messages from foreign channel

### ISSUE THREAD

**Issue by Farzat07** [knadh/tg-archive#40]
While archiving messages from a public channel, messages from another channel `@DebugSchool` where included in the built website. Is this behaviour expected? And how can these messages be removed?

With the introduction of sponsors, I'm afraid that these might be sponsor messages. If that is the case, I believe an option to exclude these when building the website, or at least the rss feed, would be a good idea.

**Comment by Farzat07** [comment]
Ok seems the problem can be avoided by deleting data.sqlite and starting over, but still I don't get why is this happening.

**Comment by knadh** [comment]
Ah, no clue how this could've happened. If the Telegram API returned those messages, these may be legitimate (sponsor?) like you said.

Will add an `--exclude-users=[]` flag to filter out messages from certain user IDs.

**Comment by faraazb** [comment]
It is a sponsored message, most probably. Although, excluding messages by user id would be a nice addition for many other purposes, excluding sponsored messages this way would still be a good amount of work as these messages could be from different senders  at different times and one would have to figure out who they are.
Also, I am not sure how the new sponsored messages terms of service works or if it is even applicable in the context of tg-archive. Not "displaying" these messages is considered as a violation of the Telegram API's terms of service from what they have on the TOS and sponsored messages page.

**Comment by knadh** [comment]
> this way would still be a good amount of work as these messages could be from different senders at different times and one would have to figure out who they are.

Yep, fair point.

>  Also, I am not sure how the new sponsored messages terms of service works or if it is even applicable in the context of tg-archive. Not "displaying" these messages is considered as a violation of the Telegram API's terms of service from what they have on the TOS and sponsored messages page.

https://core.telegram.org/api/terms

> 3.3. If your app allows accessing content from Telegram channels, you must include support for official sponsored messages in Telegram channels and may not interefere with this functionality.

This is very interesting. For live telegram clients, it might make sense, but what about in the context of export and archival. Tricky.

**Comment by Farzat07** [comment]
Actually I figured out the source of the problem.

Though the sponsored messages are gonna probably appear sometime and will have to be dealt with, this current case is unrelated.

It seems that the pip installation on my Ubuntu server had a data.sqlite file in the example/ directory, which is copied when a new archive is created. This data.sqlite had for some reason these messages from `@DebugSchool`.

> Ok seems the problem can be avoided by deleting data.sqlite and starting over, but still I don't get why is this happening.
This explains the case. The data.sqlite was the initial culprit, so deleting it solves the issue.

This problem only happened on my Ubuntu server for some reason. On my local Arch machine, there is no data.sqlite file in the example/ directory, possibly because I am installing from git.

I will try uninstalling and installing the package again to see if the file appears again.

**Comment by Farzat07** [comment]
Ok yup, same problem persists.

**Comment by knadh** [comment]
Whoa, I've been accidentally packaging test data/session files in the pip releases from my machine! They must've ended up in the `example` directory while testing and I missed them because they're untracked files in git.

Just pushed a release `v0.5.3` that doesn't have it. Will try and move PyPi publishing to a GitHub workflow soon.
