### ISSUE TITLE
Symlinks instead of copy.

### ISSUE THREAD

**Issue by 3h5t4tvz8etx1op2** [knadh/tg-archive#42]
Hi!

From what I see the `--build` flag copy whole media folder:

https://github.com/knadh/tg-archive/blob/d28d7c53b8dc9f40378735f822aa532e49fe14ae/tgarchive/build.py#L177

How about switching to symlinks? They can safe half of the storage

**Comment by knadh** [comment]
Yep, makes sense. Will add this.
