### ISSUE TITLE
Run as bot

### ISSUE THREAD

**Issue by Seele0oO** [knadh/tg-archive#57]
```python
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetDialogsRequest)
```
It does not appear to support running as a bot.
bot has been granted group administrator privileges and has permission to read messages.
Will it support running in bot?

**Comment by knadh** [comment]
Only the non-bot user API supports pulling messages. This is documented in the README: https://github.com/knadh/tg-archive#install
