### ISSUE TITLE
Support takeout mode

### ISSUE THREAD

**Issue by Lonami** [knadh/tg-archive#6]
It's the mode used by Telegram Desktop to export chats. Basically, it wraps every request in a "takeout session", which presumably lowers limits (as in, you can `iter_messages` with a `wait_time=0`). I took a quick look at the project files and it doesn't seem to be used yet. See documentation at [`client.takeout`](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.account.AccountMethods.takeout) for usage.

**Comment by knadh** [comment]
That sounds great, @faraazb. Please go ahead and send a PR.

**Comment by faraazb** [comment]
Sure! I will make a PR soon.
