### ISSUE TITLE
does not complete the export process

### ISSUE THREAD

**Issue by KonstantinDjairo** [knadh/tg-archive#67]
i'm getting an error with messages that was excluded and it does not let me complete the export process

the error:
> https://imgur.com/a/wD7LBas

can we skip those ID's of messages that was deleted without interrupting the whole export process?

**Comment by knadh** [comment]
Those are just warnings and do not affect the sync. The last line in your screenshot says that the sync finished and fetched 8521 messages.

**Comment by KonstantinDjairo** [comment]
> 

they do affect the sync, it interrupt the process and don't donwload the rest of the files

**Comment by knadh** [comment]
That is not apparent in the screenshot you shared though. It just shows reports of non-downloadable files.
