### ISSUE TITLE
Pagination taking so much space

### ISSUE THREAD

**Issue by Markfeller** [knadh/tg-archive#76]
https://github.com/knadh/tg-archive/blob/32240224f1a49b52aead1c8a4c20de4ce52f3bd4/tgarchive/example/template.html#L77

current pagination-top list is listing all of the page available in that month. this is taking a lot of screen spaces

example: https://explore.osintukraine.com/, on July 2022 there is 87k messages/176 pages. almost half of my screen is gone just for pagination.

current pagination :
![image](https://user-images.githubusercontent.com/107292058/180693084-66c08ae9-aff7-4bcd-954c-f13e2f4a3be6.png)
proposed pagination : 
![image](https://user-images.githubusercontent.com/107292058/180693638-d3dc1676-1d74-49c1-ad95-875b6f96c614.png)

**Comment by knadh** [comment]
![image](https://user-images.githubusercontent.com/547147/183247494-fb0c05fc-37a0-47bf-8bac-1e4ce3396903.png)

Add a simple CSS fix instead that adds a vertical scrollbar after a few lines of pagination. The `...` ellipsis solution requires JS and is difficult to pull off across customisations to the theme.
