### ISSUE TITLE
Temporary file was not removed after failed download

### ISSUE THREAD

**Issue by qk-li** [knadh/tg-archive#78]
After enconcting download error eg.
"The file reference has expired and is not no longer valid or it belongs to self-destructing media and cannot be resent (caused by GetFileRequest)", the partially downloaded temporary file will not be deleted.

**Comment by knadh** [comment]
This is a message from Telegram. Is the sync breaking at that point or does it continue to work?

**Comment by qk-li** [comment]
> This is a message from Telegram. Is the sync breaking at that point or does it continue to work?

The sync continues, but the unfinished temporary files is left over under /tmp. I have a quite unstable Internet here. I guess this error may come from that.
