### ISSUE TITLE
Is there any support for Normal chats?

### ISSUE THREAD

**Issue by sabrysm** [knadh/tg-archive#85]
I was wondering if tg-archive has a support for backing up normal chats between two persons

**Comment by knadh** [comment]
I haven't tested this, but if you can get the conversation's "channel ID", it might just work.

**Comment by sabrysm** [comment]
> I haven't tested this, but if you can get the conversation's "channel ID", it might just work.

Yep it worked by passing the name of the friend. btw is it normal that _template.html_ looks [like this](https://prnt.sc/4mJfpZSx6Gs0) before I run `tg-archive --build` ?

**Comment by knadh** [comment]
Yes, that's the Jinja template file. Once you run `--build`, the actual site is created in the `site` directory.

**Comment by sabrysm** [comment]
ok so when I do `tg-archive --sync` does it look for changes only and then updates it? or it re-render the whole chat again? Not sure how it works

**Comment by knadh** [comment]
`--sync` pulls new updates and stores it in the local database. `--build` regenerates the static site from scratch including all new changes.

**Comment by sabrysm** [comment]
Thanks

**Comment by sabrysm** [comment]
Sorry I still have some Questions:
1) Does the application tg-archive output lookup things dynamically?  
2) How does it handle Messages with comments?   Does it download the comments?

**Comment by knadh** [comment]
1) Unsure what you mean by this.

2) Replies are linked to the parent.

Check out this site: https://tg.fossunited.org
