### ISSUE TITLE
Exporting thumbnails instead of original files

### ISSUE THREAD

**Issue by UtopianElectronics** [knadh/tg-archive#87]
Is it possible to export thumbnails of media files instead of the original media files to save space and internet data usage?

**Comment by knadh** [comment]
I don't think it's possible to download only the thumbnail. It comes as a part of the full media download. Media (and thumb) download can be disabled fully though.

**Comment by UtopianElectronics** [comment]
>Media (and thumb) download can be disabled fully though.

How? Is it possible to get a referring link to them to be able to download them later?

**Comment by knadh** [comment]
`download_media: False` in config.toml. Telegram doesn't expose a download URL unfortunately.
