### ISSUE TITLE
Showing Error and help requested

### ISSUE THREAD

**Issue by animeworld0310** [knadh/tg-archive#90]
Issue:
when i run this command pip3 install tg-archive , it shows error and doesn't get's installed successfully 

I have attached image below

Help:
And also make a video on how to run this thing it will help a lot

![Screenshot (33)](https://user-images.githubusercontent.com/73987648/214900787-c7f1d6f9-be7e-4433-9315-b7667cb4f211.png)

**Comment by knadh** [comment]
Looks like a Windows specific issue. I don't have a Windows system, so unable to look into this.

That said, figuring out a way to install the`cryptg` package first (maybe there's a Windows .msi installer for it somewhere) and then trying might help.

**Comment by Seele0oO** [comment]
I think it will help:
1. install cryptg firstly
    with pip or the whl file which it's title contain "win"
    https://pypi.org/project/cryptg/#files
2. by the way,if it's faild too.you may need install the C/C++ develop tools or runtime,I'm not sure.
3. run ```pip install tg-archive``` again
if there is any unexpect error,please attach screenshots or log.
